version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  app1:
    build: ./app1
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq

  app2:
    build: ./app2
    ports:
      - '3001:3001'
    depends_on:
      - rabbitmq